server:
  port: 7776
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://root:123456@localhost:7776/eureka/
security:
  user:
    name: root
    password: 123456