spring:
  datasource:
    url: jdbc:mysql://192.168.9.151:3306/dm_base?useUnicode=true&characterEncoding=gbk&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: dm-base-provider
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@localhost:7776/eureka/
moduleName: dm-base-provider
server:
  port: 7002
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
